### ISSUE TITLE
Pipeline Serving 的 config.yml 能否支持环境变量？

### ISSUE THREAD

**Issue by Jnoee** [PaddlePaddle/Serving#1397]
有些配置参数希望能够动态传入，例如我希望根据机器的配置来确定GPU、进程数等，配置文件能否支持环境变量？
例如：
worker_num: $WORKER_NUM
表示从系统环境变量获取该值。

**Comment by TeslaZhao** [comment]
对于全局的变量如worker_num是可以从系统环境中动态读入，但对于每个OP可设置参数是不同的（例如CPU/GPU id/TRT、并发数、local/rpc等），不适合从系统环境变量中读取差异化数据，通用设计上是非常复杂的。我的想法是说您可以针对您的业务场景，独立实现一套文本替换规则重新生成config.yml，方案：

1.生成一个备份配置文件config.yml.bak，并将从环境变量替换的变量用{}标记，如worker_num: {WORKER_NUM}。
2.设置系统环境变量
3.实现一个sh脚本，每次服务启动前运行sh脚本，使用系统环境变量替换占位符，重新生成config.yml
4.启动服务

**Comment by Jnoee** [comment]
用sh脚本是可以实现，更希望原生能支持，用起来会比较方便。
类似spring boot的配置文件，可以支持默认值、环境变量和运行时参数替换。
请考虑下这个特性，谢谢。

**Comment by TeslaZhao** [comment]
好的，感谢您的建议，我们内部会讨论这个特性，运行时参数替换是热加载配置？

**Comment by Jnoee** [comment]
类似于spring boot的配置文件机制，例如：
```

rpc_port: ${RPC_PORT:18092} # 优先 $RPC_PORT 环境变量，如果没有则使用默认值 18092
http_port: ${HTTP_PORT:9292} # 同上
worker_num: ${WORKER_NUM} # 从环境变量获取
...
dag:
    is_thread_op: False
    retry: 10
    use_profile: False
    ...

```
设置环境变量，运行时可读取环境变量的值。
另运行时可通过传参 --dag.is_thread_op=True --dag.retry=3 来覆盖配置文件中对应的配置项。
