### ISSUE TITLE
paddleserving 配置gpu启动却没有使用gpu

### ISSUE THREAD

**Issue by Enchanted0911** [PaddlePaddle/Serving#1728]
版本信息：
    paddleserving-gpu 版本 0.7.0.post.112
    cuda版本11.4
问题描述：
    我在使用paddleserving pipline部署时，配置文件配置使用gpu，但服务却没有使用我的gpu，于是我把配置文件改成使用cpu，服务启动资源占用情况和配置为gpu时启动一致。貌似配置文件配置使用设备不起作用？
以下是我的配置：

```
rpc_port: 18091
http_port: 9998

worker_num: 20

build_dag_each_worker: False

dag:
    is_thread_op: False
    retry: 1
    use_profile: False
    tracer:
        interval_s: 60
op:
    pre:
        concurrency: 10
        local_service_conf:
            model_config: ./models/qwer/qwer__cls_1.4_serving
            devices: "0" # "0,1"
            client_type: local_predictor
            fetch_list: ["softmax_1.tmp_0"] 
    imgdet:
        concurrency: 10
        local_service_conf:
            model_config: ./models/qwer/qwer_imgdet_1.0_serving
            devices: "0" # "0,1"
            client_type: local_predictor
            fetch_list: ["multiclass_nms3_0.tmp_0"] 
    det:
        concurrency: 4
        local_service_conf:
            client_type: local_predictor
            model_config: ./models/qwer/qwer_det_1.1_serving
            fetch_list: ["sigmoid_2.tmp_0"]
            devices: "0"
            ir_optim: True
    rec:
        concurrency: 2
        timeout: -1
        retry: 1
        local_service_conf:
            client_type: local_predictor
            model_config: ./models/qwer/qwer_rec_1.4_serving
            fetch_list: ["softmax_1.tmp_0"]  
            devices: "0"
            ir_optim: True
```
在该配置下的资源占用情况如下：
![gpu_status](https://user-images.githubusercontent.com/65162523/159109216-e4e7ca5e-d45c-4bb3-a691-d581409d1efa.png)
![cpu1](https://user-images.githubusercontent.com/65162523/159109478-3fe92054-dbda-4078-89ec-8a978dd41508.png)
