### ISSUE TITLE
Serving采用docker部署的方式，返回的结果是空的

### ISSUE THREAD

**Issue by xiulianzw** [PaddlePaddle/Serving#1834]
![image](https://user-images.githubusercontent.com/20657139/183828094-2a28e6f6-f70b-496e-96ed-86955dc789c0.png)
采用的是docker的方式进行部署的**registry.baidubce.com/paddlepaddle/serving:0.8.3-cuda10.1-cudnn7-runtime**
配置文件config.xml的内容如下：
```
#rpc端口, rpc_port和http_port不允许同时为空。当rpc_port为空且http_port不为空时，会自动将rpc_port设置为http_port+1
rpc_port: 18090

#http端口, rpc_port和http_port不允许同时为空。当rpc_port可用且http_port为空时，不自动生成http_port
http_port: 9999

#worker_num, 最大并发数。当build_dag_each_worker=True时, 框架会创建worker_num个进程，每个进程内构建grpcSever和DAG
##当build_dag_each_worker=False时，框架会设置主线程grpc线程池的max_workers=worker_num
worker_num: 10

#build_dag_each_worker, False，框架在进程内创建一条DAG；True，框架会每个进程内创建多个独立的DAG
build_dag_each_worker: False

dag:
    #op资源类型, True, 为线程模型；False，为进程模型
    is_thread_op: False

    #重试次数,默认是10
    retry: 1

    #使用性能分析, True，生成Timeline性能数据，对性能有一定影响；False为不使用
    use_profile: False
    
    tracer:
        interval_s: 10
op:
    det:
        #并发数，is_thread_op=True时，为线程并发；否则为进程并发
        concurrency: 4
        
        #Serving交互重试次数，默认不重试
        #retry: 3

        #当op配置没有server_endpoints时，从local_service_conf读取本地服务配置
        local_service_conf:
            #client类型，包括brpc, grpc和local_predictor.local_predictor不启动Serving服务，进程内预测
            client_type: local_predictor

            #det模型路径
            model_config: ./inference/ppocrv3_det_serving

            #Fetch结果列表，以client_config中fetch_var的alias_name为准，不设置默认取全部输出变量
            fetch_list: ["sigmoid_0.tmp_0"]
            
            # 批量查询Serving的数量, 默认1。batch_size>1要设置auto_batching_timeout，否则不足batch_size时会阻塞
            # batch_size: 16
            # 批量查询超时，与batch_size配合使用
            # auto_batching_timeout: 2000
            

            # device_type, 0=cpu, 1=gpu, 2=tensorRT, 3=arm cpu, 4=kunlun xpu, 5=arm ascend310, 6=arm ascend910
            #device_type: 2

            #计算硬件ID，当devices为""或不写时为CPU预测；当devices为"0", "0,1,2"时为GPU预测，表示使用的GPU卡
            devices: "0"
            
            # use_mkldnn, 开启mkldnn时，必须同时设置ir_optim=True，否则无效
            # use_mkldnn: True
            
            # thread_num: 2   
            # ir_optim, 开启TensorRT时，必须同时设置ir_optim=True，否则无效
            ir_optim: True

            # precsion, 预测精度，降低预测精度可提升预测速度
            # GPU 支持: "fp32"(default), "fp16", "int8"
            # precision: "fp32"

    rec:
        #并发数，is_thread_op=True时，为线程并发；否则为进程并发
        concurrency: 2

        #超时时间, 单位ms
        timeout: -1
 
        #Serving交互重试次数，默认不重试
        #retry: 3

        #当op配置没有server_endpoints时，从local_service_conf读取本地服务配置
        local_service_conf:

            #client类型，包括brpc, grpc和local_predictor。local_predictor不启动Serving服务，进程内预测
            client_type: local_predictor

            #rec模型路径
            model_config: ./inference/ppocrv3_rec_serving

            #Fetch结果列表，以client_config中fetch_var的alias_name为准, 不设置默认取全部输出变量
            fetch_list: ["softmax_5.tmp_0"]
            
            # 批量查询Serving的数量, 默认1。batch_size>1要设置auto_batching_timeout，否则不足batch_size时会阻塞
            # batch_size: 16
            # 批量查询超时，与batch_size配合使用
            # auto_batching_timeout: 2000
            
            

            #计算硬件ID，当devices为""或不写时为CPU预测；当devices为"0", "0,1,2"时为GPU预测，表示使用的GPU卡
            devices: "0"

            #device_type, 0=cpu, 1=gpu, 2=tensorRT, 3=arm cpu, 4=kunlun xpu, 5=arm ascend310, 6=arm ascend910
            #device_type: 2

            # use_mkldnn, 开启mkldnn时，必须同时设置ir_optim=True，否则无效
            # use_mkldnn: True
            
            # thread_num: 2
            ir_optim: True

            # precsion, 预测精度，降低预测精度可提升预测速度
            # GPU 支持: "fp32"(default), "fp16", "int8"
            # precision: "fp32"
```
