### ISSUE TITLE
基于HTTP 接口请求 PaddleSeving 服务，未识别 post 参数中body 的内容

### ISSUE THREAD

**Issue by yang9112** [PaddlePaddle/Serving#1852]
使用以下配置启动服务，使用 http 接口请求服务时：

<img width="980" alt="image" src="https://user-images.githubusercontent.com/6162257/190552756-ef3cbf4c-ec62-4b11-a80c-631bd3c491b4.png">

查看web_server.py 中的 input_dict打印结果，发现没有传入任何参数，这个是为什么？

{'@DAGExecutor': {}}

```
# worker_num, 最大并发数。当build_dag_each_worker=True时, 框架会创建worker_num个进程，每个进程内构建grpcSever和DAG
# 当build_dag_each_worker=False时，框架会设置主线程grpc线程池的max_workers=worker_num
worker_num: 10
# build_dag_each_worker, False，框架在进程内创建一条DAG；True，框架会每个进程内创建多个独立的DAG
build_dag_each_worker: false

dag:
  # op资源类型, True, 为线程模型；False，为进程模型
  is_thread_op: False
  # 使用性能分析, True，生成Timeline性能数据，对性能有一定影响；False为不使用
  tracer:
    interval_s: 10

# http端口, rpc_port和http_port不允许同时为空。当rpc_port可用且http_port为空时，不自动生成http_port
http_port: 18082
# rpc端口, rpc_port和http_port不允许同时为空。当rpc_port为空且http_port不为空时，会自动将rpc_port设置为http_port+1
rpc_port: 8088

op:
  bert:
    # 并发数，is_thread_op=True时，为线程并发；否则为进程并发
    concurrency: 2

    # 当op配置没有server_endpoints时，从local_service_conf读取本地服务配置
    local_service_conf:
      # client类型，包括brpc, grpc和local_predictor.local_predictor不启动Serving服务，进程内预测
      client_type: local_predictor
      #ir_optim
      ir_optim: True
      # device_type, 0=cpu, 1=gpu, 2=tensorRT, 3=arm cpu, 4=kunlun xpu
      device_type: 2
      # 计算硬件ID，当devices为""或不写时为CPU预测；当devices为"0", "0,1,2"时为GPU预测，表示使用的GPU卡
      devices: '0'
      # Fetch结果列表，以client_config中fetch_var的alias_name为准, 如果没有设置则全部返回
      # fetch_list: "output"
      pricision: "fp16"
      # 模型路径
      model_config: serving_server
```
