### ISSUE TITLE
请问有部署多个模型串联的pipeline模式的文档或者范例吗？用ocr那个不起作用，卡了两天了

### ISSUE THREAD

**Issue by dlmkaq55240** [PaddlePaddle/Serving#1886]
目前我是想实现paddlex 范例中的meter_reader 的det + seg 两个模型的pipeline模式的部署，det的通了，但是到seg 这里的时候，后处理总是报错，试了很多方法都不行，希望能获得帮助，也在aistudio和谷歌上搜了很多，都没找到这样的范例，希望能有个文档或者例子都可以
下面是我的webservice.py文件

```
from paddle_serving_server.web_service import WebService, Op
import numpy as np
import cv2
from paddle_serving_app.reader import *
import base64
from io import BytesIO
from PIL import Image

class MeterReader(Op):
    def init_op(self):
        # 这里 compose 一些需要的预处理操作
        self.img_preprocess = Sequential([
            BGR2RGB(), Div(255.0),
            Normalize([0.5, 0.5, 0.5], [0.5, 0.5, 0.5], False),
            Resize((512, 512)), Transpose((2, 0, 1))
        ])

        self.img_postprocess = SegPostprocess(3)

    def preprocess(self, input_dicts, data_id, log_id):
        (_, input_dict), = input_dicts.items()
        imgs = []
        #print("keys", input_dict.keys())
        for key in input_dict.keys():
            if input_dict[key].startswith('data:image'):
                image_str = input_dict[key]
                image_str = image_str[image_str.find(';base64,') + 8:]
            data = base64.b64decode(image_str.encode('utf8'))
            data = np.fromstring(data, np.uint8)
            im = cv2.imdecode(data, cv2.IMREAD_COLOR)
            
            im = self.img_preprocess(im)
            imgs.append({
                "image": im[np.newaxis, :]
            })
        feed_dict = {
            "image": np.concatenate(
                [x["image"] for x in imgs], axis=0)
        }
        image = im[np.newaxis, :]
        # print(image)
        return feed_dict, False, None, ""

    def postprocess(self, input_dicts, fetch_dict, data_id, log_id):
        print(fetch_dict)
        fetch_dict['filename'] = "/home/output.jpg"
        res_dict = {
            "bbox_result":
            str(self.img_postprocess(
                image_with_result=fetch_dict))
        }
        return res_dict, None, ""

# 其余的都是固定的操作
class MeterSetService(WebService):
    def get_pipeline_response(self, read_op):
        meter_set_op = MeterReader(name="meter_seg", input_ops=[read_op])
        return meter_set_op

# define the service class
uci_service = MeterSetService(name="meter_seg")
# load config and prepare the service
uci_service.prepare_pipeline_config("config.yml")
# start the service
uci_service.run_service()
```

serving_server_conf.prototxt
```
feed_var {
  name: "image"
  alias_name: "image"
  is_lod_tensor: false
  feed_type: 1
  shape: 3
}
fetch_var {
  name: "save_infer_model/scale_0.tmp_1"
  alias_name: "save_infer_model/scale_0.tmp_1"
  is_lod_tensor: false
  fetch_type: 1
  shape: 3
}

```

config.yml
```
dag:
  #op资源类型, True, 为线程模型；False，为进程模型
  is_thread_op: false
  #使用性能分析, True，生成Timeline性能数据，对性能有一定影响；False为不使用
  tracer:
    interval_s: 30
#http端口, rpc_port和http_port不允许同时为空。当rpc_port可用且http_port为空时，不自动生成http_port
http_port: 18082
op:
  meter_seg:
    #并发数，is_thread_op=True时，为线程并发；否则为进程并发
    concurrency: 10
    local_service_conf:
      #client类型，包括brpc, grpc和local_predictor.local_predictor不启动Serving服务，进程内预测
      client_type: local_predictor
      # device_type, 0=cpu, 1=gpu, 2=tensorRT, 3=arm cpu, 4=kunlun xpu
      device_type: 0
      #计算硬件ID，当devices为""或不写时为CPU预测；当devices为"0", "0,1,2"时为GPU预测，表示使用的GPU卡
      devices: ''
      #Fetch结果列表，以bert_seq128_model中fetch_var的alias_name为准, 如果没有设置则全部返回
      fetch_list:
      - save_infer_model/scale_0.tmp_1
      #模型路径
      model_config: /home/models/meter_reader/models/meter_seg_model/server/
  

#rpc端口, rpc_port和http_port不允许同时为空。当rpc_port为空且http_port不为空时，会自动将rpc_port设置为http_port+1
#rpc_port: 9998
#worker_num, 最大并发数。当build_dag_each_worker=True时, 框架会创建worker_num个进程，每个进程内构建grpcSever和DAG
#当build_dag_each_worker=False时，框架会设置主线程grpc线程池的max_workers=worker_num
worker_num: 20
```

求帮助，真的是没有办法了，能找的方法都找了。
