### ISSUE TITLE
在op添加set_dynamic_shape_info函数指定输入大小，还是会报错

### ISSUE THREAD

**Issue by heyuhhh** [PaddlePaddle/Serving#1890]
我在DetOp中添加set_dynamic_shape_info函数，具体如下：
```
    def set_dynamic_shape_info(self):
        min_input_shape = {
            "x": [1, 3, 64, 64],
            "batch_norm_23.tmp_3.tmp": [1, 512, 8, 8],
            "relu_5.tmp_0": [1, 512, 8, 8],
            "batch_norm_10.tmp_3.tmp": [1, 256, 16, 16],
            "relu_1.tmp_0": [1, 256, 16, 16],
            "conv2d_120.tmp_0.tmp": [1, 256, 2, 2],
            "conv2d_121.tmp_0.tmp": [1, 256, 4, 4],
            "conv2d_122.tmp_0.tmp": [1, 256, 8, 8],
            "conv2d_123.tmp_0.tmp": [1, 256, 16, 16],
            "conv2d_124.tmp_0.tmp": [1, 64, 2, 2],
            "conv2d_125.tmp_0.tmp": [1, 64, 4, 4],
            "conv2d_126.tmp_0.tmp": [1, 64, 8, 8],
            "conv2d_127.tmp_0.tmp": [1, 64, 16, 16],
            "batch_norm_42.tmp_3.tmp": [1, 1024, 4, 4],
            "relu_11.tmp_0": [1, 1024, 4, 4],
            "nearest_interp_v2_24501.tmp_0": [1, 64, 16, 16],
            "nearest_interp_v2_24502.tmp_0": [1, 64, 16, 16],
            "nearest_interp_v2_24503.tmp_0": [1, 64, 16, 16],
            "sigmoid_16.tmp_0.tmp": [1, 4, 16, 16],
            "batch_norm_10.tmp_3": [1, 256, 16, 16],
        }
        max_input_shape = {
            "x": [1, 3, 960, 960],
            "batch_norm_23.tmp_3.tmp": [1, 512, 120, 120],
            "relu_5.tmp_0": [1, 512, 120, 120],
            "batch_norm_10.tmp_3.tmp": [1, 256, 240, 240],
            "relu_1.tmp_0": [1, 256, 240, 240],
            "conv2d_120.tmp_0.tmp": [1, 256, 30, 30],
            "conv2d_121.tmp_0.tmp": [1, 256, 60, 60],
            "conv2d_122.tmp_0.tmp": [1, 256, 120, 120],
            "conv2d_123.tmp_0.tmp": [1, 256, 240, 240],
            "conv2d_124.tmp_0.tmp": [1, 64, 30, 30],
            "conv2d_125.tmp_0.tmp": [1, 64, 60, 60],
            "conv2d_126.tmp_0.tmp": [1, 64, 120, 120],
            "conv2d_127.tmp_0.tmp": [1, 64, 240, 240],
            "batch_norm_42.tmp_3.tmp": [1, 1024, 60, 60],
            "relu_11.tmp_0": [1, 1024, 60, 60],
            "nearest_interp_v2_24501.tmp_0": [1, 64, 240, 240],
            "nearest_interp_v2_24502.tmp_0": [1, 64, 240, 240],
            "nearest_interp_v2_24503.tmp_0": [1, 64, 240, 240],
            "sigmoid_16.tmp_0.tmp": [1, 4, 240, 240],
            "batch_norm_10.tmp_3": [1, 256, 240, 240],
        }
        opt_input_shape = {
            "x": [1, 3, 64, 64],
            "batch_norm_23.tmp_3.tmp": [1, 512, 8, 8],
            "relu_5.tmp_0": [1, 512, 8, 8],
            "batch_norm_10.tmp_3.tmp": [1, 256, 16, 16],
            "relu_1.tmp_0": [1, 256, 16, 16],
            "conv2d_120.tmp_0.tmp": [1, 256, 2, 2],
            "conv2d_121.tmp_0.tmp": [1, 256, 4, 4],
            "conv2d_122.tmp_0.tmp": [1, 256, 8, 8],
            "conv2d_123.tmp_0.tmp": [1, 256, 16, 16],
            "conv2d_124.tmp_0.tmp": [1, 64, 2, 2],
            "conv2d_125.tmp_0.tmp": [1, 64, 4, 4],
            "conv2d_126.tmp_0.tmp": [1, 64, 8, 8],
            "conv2d_127.tmp_0.tmp": [1, 64, 16, 16],
            "batch_norm_42.tmp_3.tmp": [1, 1024, 4, 4],
            "relu_11.tmp_0": [1, 1024, 4, 4],
            "nearest_interp_v2_24501.tmp_0": [1, 64, 16, 16],
            "nearest_interp_v2_24502.tmp_0": [1, 64, 16, 16],
            "nearest_interp_v2_24503.tmp_0": [1, 64, 16, 16],
            "sigmoid_16.tmp_0.tmp": [1, 4, 16, 16],
            "batch_norm_10.tmp_3": [1, 256, 16, 16],
        }
        self.dynamic_shape_info = {
            "min_input_shape": min_input_shape,
            "max_input_shape": max_input_shape,
            "opt_input_shape": opt_input_shape,
        }
```
使用tensorrt和int8进行推理，config文件内容如下：
```
#rpc端口, rpc_port和http_port不允许同时为空。当rpc_port为空且http_port不为空时，会自动将rpc_port设置为http_port+1
rpc_port: 18091

#http端口, rpc_port和http_port不允许同时为空。当rpc_port可用且http_port为空时，不自动生成http_port
http_port: 9998

#worker_num, 最大并发数。当build_dag_each_worker=True时, 框架会创建worker_num个进程，每个进程内构建grpcSever和DAG
##当build_dag_each_worker=False时，框架会设置主线程grpc线程池的max_workers=worker_num
worker_num: 32

#build_dag_each_worker, False，框架在进程内创建一条DAG；True，框架会每个进程内创建多个独立的DAG
build_dag_each_worker: False

dag:
    #op资源类型, True, 为线程模型；False，为进程模型
    is_thread_op: False

    #重试次数
    retry: 10

    #使用性能分析, True，生成Timeline性能数据，对性能有一定影响；False为不使用
    use_profile: True
    
    tracer:
        interval_s: 10
op:
    det:
        #并发数，is_thread_op=True时，为线程并发；否则为进程并发
        concurrency: 16

        #当op配置没有server_endpoints时，从local_service_conf读取本地服务配置
        local_service_conf:
            #client类型，包括brpc, grpc和local_predictor.local_predictor不启动Serving服务，进程内预测
            client_type: local_predictor

            #det模型路径
            model_config: ./ppocr_det_db++_qt_serving

            #Fetch结果列表，以client_config中fetch_var的alias_name为准，不设置默认取全部输出变量
            #fetch_list: ["sigmoid_0.tmp_0"]
            #计算硬件类型: 空缺时由devices决定(CPU/GPU)，0=cpu, 1=gpu, 2=tensorRT, 3=arm cpu, 4=kunlun xpu
            device_type: 2

            precision: "int8"
            use_calib: True
            #计算硬件ID，当devices为""或不写时为CPU预测；当devices为"0", "0,1,2"时为GPU预测，表示使用的GPU卡
            devices: "0,1,2,3"
            
            ir_optim: True
    rec:
        #并发数，is_thread_op=True时，为线程并发；否则为进程并发
        concurrency: 8

        #超时时间, 单位ms
        timeout: -1
 
        #Serving交互重试次数，默认不重试
        retry: 1

        #当op配置没有server_endpoints时，从local_service_conf读取本地服务配置
        local_service_conf:

            #client类型，包括brpc, grpc和local_predictor。local_predictor不启动Serving服务，进程内预测
            client_type: local_predictor

            #rec模型路径
            model_config: ./ppocr_rec_svtr_serving

            #Fetch结果列表，以client_config中fetch_var的alias_name为准, 不设置默认取全部输出变量
            #fetch_list: 

            #计算硬件类型: 空缺时由devices决定(CPU/GPU)，0=cpu, 1=gpu, 2=tensorRT, 3=arm cpu, 4=kunlun xpu
            device_type: 0

            # precision: "int8"

            #计算硬件ID，当devices为""或不写时为CPU预测；当devices为"0", "0,1,2"时为GPU预测，表示使用的GPU卡
            devices: "0,1,2,3"
            
            ir_optim: True

```

运行客户端python文件，还是会报下面的错误：
I1126 09:08:41.038064 25636 tensorrt_engine_op.h:421] This process is generating calibration table for Paddle TRT int8...
I1126 09:08:41.049059 27658 tensorrt_engine_op.h:301] Prepare TRT engine (Optimize model structure, Select OP kernel etc). This process may cost a lot of time.
terminate called after throwing an instance of 'phi::enforce::EnforceNotMet'
  what():  (InvalidArgument) The input [batch_norm_10.tmp_3.tmp] shape of trt subgraph is [-1,256,-1,-1], please enable trt dynamic_shape mode by SetTRTDynamicShapeInfo. (at /paddle/paddle/fluid/inference/tensorrt/engine.h:104)

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   std::thread::_State_impl<std::thread::_Invoker<std::tuple<paddle::operators::TensorRTEngineOp::RunCalibration(paddle::framework::Scope const&, phi::Place const&) const::{lambda()#1}> > >::_M_run()
1   paddle::operators::TensorRTEngineOp::PrepareTRTEngine(paddle::framework::Scope const&, paddle::inference::tensorrt::TensorRTEngine*) const
2   paddle::inference::tensorrt::OpConverter::ConvertBlockToTRTEngine(paddle::framework::BlockDesc*, paddle::framework::Scope const&, std::vector<std::string, std::allocator<std::string > > const&, std::unordered_set<std::string, std::hash<std::string >, std::equal_to<std::string >, std::allocator<std::string > > const&, std::vector<std::string, std::allocator<std::string > > const&, paddle::inference::tensorrt::TensorRTEngine*)

----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1669453721 (unix time) try "date -d @1669453721" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x6424) received by PID 25636 (TID 0x7fda69ffb700) from PID 25636 ***]

请问这是为什么呢？batch_norm_10.tmp_3.tmp 这个模块的大小上面已经指定了
